FROM golang:1.17-alpine AS builder

WORKDIR /app

ADD go.mod .

RUN go mod download

COPY . .

RUN go build -o backend main.go

FROM alpine

WORKDIR /app
COPY --from=builder /app/config.env /app/
COPY --from=builder /app/backend /app/backend
CMD ["./backend"]